### ISSUE TITLE
Attempting to install and test on a new machine

### ISSUE THREAD

**Issue by sealauren** [mindriot101/ttvfast-python#16] opened 2018-05-01 17:32 UTC
Hi Simon,

I'm trying to run ttvfast-python on a new machine (a large server) using c-shell.  My python installation is miniconda2.  I cloned ttvfast-python into my home directory and followed the README instructions for installing ttvfast-python (including the external ttvfast).  I have also added the ttvfast-python directory to my path.  When I try running py.test, I get the following error:

[lweiss@cadence ttvfast-python]$ py.test
Traceback (most recent call last):
  File "/data/user/lweiss/miniconda2/lib/python2.7/site-packages/_pytest/config.py", line 364, in _importconftest
    mod = conftestpath.pyimport()
  File "/data/user/lweiss/miniconda2/lib/python2.7/site-packages/py/_path/local.py", line 668, in pyimport
    __import__(modname)
  File "/data/user/lweiss/miniconda2/lib/python2.7/site-packages/_pytest/assertion/rewrite.py", line 212, in load_module
    py.builtin.exec_(co, mod.__dict__)
  File "/data/user/lweiss/miniconda2/lib/python2.7/site-packages/py/_builtin.py", line 221, in exec_
    exec2(obj, globals, locals)
  File "<string>", line 7, in exec2
  File "/data/user/lweiss/ttvfast-python/testing/conftest.py", line 2, in <module>
    from ttvfast import models
  File "/data/user/lweiss/ttvfast-python/ttvfast/__init__.py", line 5, in <module>
    from ._ttvfast import _ttvfast as _ttvfast_fn
ImportError: No module named _ttvfast
ERROR: could not load /data/user/lweiss/ttvfast-python/testing/conftest.py

[lweiss@cadence ttvfast-python]$ echo $PYTHONPATH
/data/user/lweiss/miniconda2/bin:/data/user/lweiss/miniconda2/lib/python2.7/site-packages/:/data/user/lweiss/ttvfast-python:/data/user/lweiss/ttvfast-python/ttvfast

Do you understand why the following import error occurs?  Is there something else I need to add to my path?  Or is there another command I need to execute to install the package?

Thanks!

Lauren

**Comment by sealauren** [comment] 2018-05-01 17:44
Here's another example:

[lweiss@cadence ttvfast-python]$ ipython
Python 2.7.14 |Anaconda, Inc.| (default, Dec  7 2017, 17:05:42) 
Type "copyright", "credits" or "license" for more information.

IPython 5.4.1 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: import ttvfast
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-bbdcab7c8dd2> in <module>()
----> 1 import ttvfast

/data/user/lweiss/ttvfast-python/ttvfast/__init__.py in <module>()
      3 "Fast TTV computation"
      4 
----> 5 from ._ttvfast import _ttvfast as _ttvfast_fn
      6 from . import models
      7 from .version import __version__  # noqa

ImportError: No module named _ttvfast

**Comment by simonrw** [comment] 2018-05-01 21:44
Hi Lauren, I'll try to take a look tomorrow night (UK time) if that's ok

**Comment by sealauren** [comment] 2018-05-02 15:36
That would be great, thank you so much!

Lauren M. Weiss, PhD
Trottier Postdoctoral Fellow
Institute of Research on Exoplanets
Université de Montréal

**Comment by simonrw** [comment] 2018-05-02 17:21
Hi Lauren, I think the issue is more to do with the documentation than the actual package. The problem is that running `python setup.py build_ext --inplace` does not install the package properly. It compiles the C code which is a good test that it is valid, but it does not install the package.

To get around this, either install from pypi: `pip install ttvfast`, or go back to the directory you cloned and run `pip install .`. You should then be able to run the tests with `pytest`/`py.test`.

I'm going to update the instructions to the ones posted below. I hope it is much clearer. Let me know what you think.

---

Installation
------------

For contributing to the package, see the [Development instructions](#development-instructions).

Install from pypi:

> `pip install ttvfast`

For the latest development version, install with pip:

> `pip install git+https://github.com/mindriot101/ttvfast.git`

### Development instructions

To contribute to `ttvfast`, clone the repository and fetch the submodule:

    git clone https://github.com/mindriot101/ttvfast-python.git
    cd ttvfast-python
    git submodule init
    git submodule update # grabs code from TTVFast

install the package, in \"development mode\" into the current python environment:

    pip install -e .

This way any python code changes made to the current directory will be reflected in the package. Note: any changes to the C code require recompilation by reinstalling the package with `pip install -e .` (see the [editable install documentation](https://pip.pypa.io/en/stable/reference/pip_install/#editable-installs) documentation for more information).

Once the package is installed, test that everything built properly
using:

    $ py.test 
    ============================== test session starts ===============================
    testing/test_lweiss.py .
    testing/test_models.py ...
    testing/test_python_api.py ...
    testing/test_ttvfast.py ...

**Comment by sealauren** [comment] 2018-05-02 17:35
Hi Simon,

I did as you suggested, but I'm still having issues.

py.test now passes:

[lweiss@cadence ttvfast-python]$ py.test

*============================= test session starts
==============================*

platform linux2 -- Python 2.7.14, pytest-3.3.0, py-1.5.2, pluggy-0.6.0

rootdir: /data/user/lweiss/ttvfast-python, inifile: pytest.ini

plugins: hypothesis-3.38.5

*collected 18 items
     *


testing/test_lweiss.py .                                                 [
5%]

testing/test_models.py ...                                               [
22%]

testing/test_python_api.py .........                                     [
72%]

testing/test_rv.py ..                                                    [
83%]

testing/test_ttvfast.py ...
[100%]


*========================== 18 passed in 0.40 seconds
===========================*


But when I try to import ttvfast, python does not like it:

[lweiss@cadence ttvfast-python]$ python

Python 2.7.5 (default, Aug 29 2016, 10:12:21)

[GCC 4.8.5 20150623 (Red Hat 4.8.5-4)] on linux2

Type "help", "copyright", "credits" or "license" for more information.

>>> import ttvfast

Traceback (most recent call last):

  File "<stdin>", line 1, in <module>

  File "ttvfast/__init__.py", line 5, in <module>

    from ._ttvfast import _ttvfast as _ttvfast_fn

ImportError: No module named _ttvfast

>>> quit()


I don't have this problem on my laptop, although my path includes the
directory containing _ttvfast.pyi in both cases.  Do you have a sense of
what's going on?

Thanks,

Lauren

Lauren M. Weiss, PhD
Trottier Postdoctoral Fellow
Institute of Research on Exoplanets
Université de Montréal

**Comment by simonrw** [comment] 2018-05-02 19:12
I notice that your `pytest` runs python 2.7.14 and your basic `python` runs python 2.7.5. It looks like you installed `ttvfast` to your 2.7.14 environment but when you call `python` it runs 2.7.5 which does not have the package.

If you run `which -a python` you will likely see at least two, one of which will be your 2.7.14. I'll bet you've installed `ttvfast` to your miniconda env but when you run `python` it defaults to your system python.

**Comment by sealauren** [comment] 2018-05-02 19:23
Yes, that fixed it, thank you!  I did not even realize there was another
version of python ahead of my miniconda installation in my path.  Thanks!

Lauren M. Weiss, PhD
Trottier Postdoctoral Fellow
Institute of Research on Exoplanets
Université de Montréal

**Comment by simonrw** [comment] 2018-05-02 21:40
No worries, thanks for helping me improve my documentation (#17). Closing this thread

**Closed as completed by simonrw** 2018-05-02 21:40 UTC
